# Railway.app deployment config
# Free $5 credit without credit card

[build]
builder = "nixpacks"

[deploy]
startCommand = "python bloomberg_simple.py"
restartPolicyType = "always"

[env]
TELEGRAM_TOKEN = "8122220616:AAFI8xFd2O0X1UiJWBWvO8j5-pgeysLCbpc"
GEMINI_API_KEY = "AIzaSyAPYV-zu5bNVFcTeElaXYWokZEk_wlAWms"
# GOOGLE_CREDENTIALS_JSON = "set manually in Railway dashboard"
